alias proxychains='proxychains -q'
alias psgpt='proxychains sgpt'
alias claer='clear'
alias ckear='clear'
alias yt-dlp='yt-dlp --cookies-from-browser $BROWSER'
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'
